### ISSUE TITLE
Hardware address exceeds maximum length

### ISSUE THREAD

**Issue by garysharp** [garysharp/DhcpServerApi#31]
A user has encountered a `ArgumentOutOfRangeException` when reading scope reservations.

```
Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: length
   at Dhcp.DhcpServerHardwareAddress.FromNative(DhcpServerHardwareType type, IntPtr pointer, Int32 length) in src\Dhcp\DhcpServerHardwareAddress.cs:line 166
   at Dhcp.Native.DHCP_CLIENT_UID.get_ClientHardwareAddress() in src\Dhcp\Native\DHCP_CLIENT_UID.cs:line 53
   at Dhcp.DhcpServerScopeReservation.FromNative(DhcpServerScope scope, DHCP_IP_RESERVATION_V4& native) in src\Dhcp\DhcpServerScopeReservation.cs:line 91
   at Dhcp.DhcpServerScopeReservation.GetReservations(DhcpServerScope scope)+MoveNext() in src\Dhcp\DhcpServerScopeReservation.cs:line 74
   ...
```

This occurred when a reservation had been configured with an invalid hardware address. Unfortunately it means the reservations and clients cannot be enumerated (as this invalid one causes the enumeration to fail).

This library receives some big efficiency boosts by treating hardware addresses as value types (living on the stack instead of needing memory allocated). Typical hardware addresses are 24 bits long. I have encountered scenarios where 128 bit hardware addresses were used. This determined a maximum supported hardware address length (16 bytes; 2 x unsigned long).

I don't know what the limit is for the Microsoft DHCP Server.

We need a way of flagging a hardware address as invalid and perhaps offering the truncated value in a way which still allows reservations/clients to be enumerated.

**Comment by garysharp** [comment]
Handled in 8e49f9b.

Enumeration of reservations/clients/leases can still continue if invalid hardware addresses are encountered.

Calling `.ToString()` on an invalid hardware address results in a truncated value followed by `...`.

A method is added `.EnsureNotTruncated()` which will throw if the value is truncated (the `Length` property could also be compared with `DhcpServerHardwareAddress.MaximumLength`).

Trying to read/convert invalid hardware addresses results in an exception.

**Comment by garysharp** [comment]
Replace `.EnsureNotTruncated()` with `.IsValid` property.
